# Stubs for gunicorn.http (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from gunicorn.http.message import Message as Message, Request as Request
from gunicorn.http.parser import RequestParser as RequestParser
