# Stubs for gunicorn.http._sendfile (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SUPPORTED_PLATFORMS: Any

def sendfile(fdout: Any, fdin: Any, offset: Any, nbytes: Any): ...
